import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/page";
import Footer from "@/components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Real Estate Consultant & properties in Nigera",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navigation/>

        {children}
        
        <Footer/>
        </body>
    </html>
  );
}
